# Generated by Django 2.0.7 on 2018-08-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('usr', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='admin@test.com', max_length=254)),
                ('pw', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JS',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='test@gmail.com', max_length=254, primary_key=True, serialize=False)),
                ('mobile', models.IntegerField(default=9876543210)),
                ('password', models.CharField(max_length=25)),
                ('education', models.CharField(max_length=60)),
                ('skils', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('resume', models.FileField(upload_to='')),
                ('profile', models.ImageField(upload_to='')),
            ],
        ),
    ]
