# Generated by Django 2.0.7 on 2018-08-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='email',
            new_name='aemail',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='pw',
            new_name='apw',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='usr',
            new_name='ausr',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='pw',
            new_name='cpw',
        ),
    ]
