# Generated by Django 2.0.7 on 2018-08-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180804_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='js',
            old_name='name',
            new_name='name_js',
        ),
    ]
