# Generated by Django 2.0.7 on 2018-08-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180804_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='js',
            old_name='skils',
            new_name='skills',
        ),
    ]
