# Generated by Django 2.0.7 on 2018-08-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180805_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=25)),
                ('e_email', models.EmailField(default='test@gmail.com', max_length=254)),
                ('e_mobile', models.IntegerField(default=9876543210)),
                ('e_exams', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='e_email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='e_exams',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='e_mobile',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='e_name',
        ),
    ]
