# Generated by Django 2.0.7 on 2018-08-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180805_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_details', models.TextField(max_length=1000)),
                ('job_type', models.CharField(max_length=50)),
                ('job_tags', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='company',
            old_name='cname',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='cpw',
            new_name='c_pw',
        ),
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AddField(
            model_name='company',
            name='c_address',
            field=models.TextField(default='Company Address', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='c_contact',
            field=models.IntegerField(default=9876543210),
        ),
        migrations.AddField(
            model_name='company',
            name='c_email',
            field=models.EmailField(default='company@gmail.com', max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exams',
            name='e_exams',
            field=models.TextField(max_length=50),
        ),
    ]
