# Generated by Django 2.0.7 on 2018-08-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180806_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='job_details',
            new_name='job_detail',
        ),
    ]
